### ISSUE TITLE
Getting stucked in some places

### ISSUE THREAD

**Issue by GomezMig03** [leozamboni/Domus#1]
I got stucked here and couldn't get out, not even jumping.
![imagen](https://github.com/user-attachments/assets/0fc4a3a8-7808-444e-8c35-90d884f43b14)
It would be good to at least have a way of reseting to the center of the church without needing to refresh the page, just teleporting the user.

**Comment by leozamboni** [comment]
Hail Mary! Thank you for opening an Issue. I just added this feature here b5563f9, feel free to test it.

**Comment by GomezMig03** [comment]
Hail Mary! The reset feature works perfectly for me.
